export default [
  {
    id: 0,
    imageUrl: "https://via.placeholder.com/300x350.png",
    prodName: "casualty",
    category: "Abaya & Hijab",
    rating: 4,
    price: 600,
    sale: 15,
  },
  {
    id: 1,
    imageUrl: "https://via.placeholder.com/300x350.png",
    prodName: "variant",
    category: "Abaya & Hijab",
    rating: 5,
    price: 700,
    sale: 25,
  },
  {
    id: 2,
    imageUrl: "https://via.placeholder.com/300x350.png",
    prodName: "berry",
    category: "Abaya & Hijab",
    rating: 3,
    price: 600,
    sale: 15,
  },
  {
    id: 3,
    imageUrl: "https://via.placeholder.com/300x350.png",
    prodName: "perform",
    category: "Abaya & Hijab",
    rating: 5,
    price: 800,
    sale: 0,
  },
  {
    id: 4,
    imageUrl: "https://via.placeholder.com/300x350.png",
    prodName: "bride",
    category: "Abaya & Hijab",
    rating: 3,
    price: 200,
    sale: 15,
  },
  {
    id: 5,
    imageUrl: "https://via.placeholder.com/300x350.png",
    prodName: "smash",
    category: "Abaya & Hijab",
    rating: 5,
    price: 600,
    sale: 15,
  },
  {
    id: 6,
    imageUrl: "https://via.placeholder.com/300x350.png",
    prodName: "stitch",
    category: "Abaya & Hijab",
    rating: 3,
    price: 300,
    sale: 15,
  },
  {
    id: 7,
    imageUrl: "https://via.placeholder.com/300x350.png",
    prodName: "referral",
    category: "Abaya & Hijab",
    rating: 5,
    price: 600,
    sale: 50,
  },
  {
    id: 8,
    imageUrl: "https://via.placeholder.com/300x350.png",
    prodName: "consciousness",
    category: "Abaya & Hijab",
    rating: 4,
    price: 400,
    sale: 15,
  },
  {
    id: 9,
    imageUrl: "https://via.placeholder.com/300x350.png",
    prodName: "offspring",
    category: "Abaya & Hijab",
    rating: 1,
    price: 600,
    sale: 0,
  },
  {
    id: 10,
    imageUrl: "https://via.placeholder.com/300x350.png",
    prodName: "knowledge",
    category: "Abaya & Hijab",
    rating: 2,
    price: 900,
    sale: 15,
  },
  {
    id: 11,
    imageUrl: "https://via.placeholder.com/300x350.png",
    prodName: "cousin",
    category: "Abaya & Hijab",
    rating: 3,
    price: 1100,
    sale: 15,
  },
  {
    id: 12,
    imageUrl: "https://via.placeholder.com/300x350.png",
    prodName: "temptation",
    category: "Abaya & Hijab",
    rating: 4,
    price: 1600,
    sale: 15,
  },
  {
    id: 13,
    imageUrl: "https://via.placeholder.com/300x350.png",
    prodName: "shallow",
    category: "Abaya & Hijab",
    rating: 5,
    price: 2600,
    sale: 15,
  },
  {
    id: 14,
    imageUrl: "https://via.placeholder.com/300x350.png",
    prodName: "XXXXXXXXXXX",
    category: "Abaya & Hijab",
    rating: 3,
    price: 1600,
    sale: 15,
  },
  {
    id: 15,
    imageUrl: "https://via.placeholder.com/300x350.png",
    prodName: "pioneer",
    category: "Abaya & Hijab",
    rating: 2,
    price: 5600,
    sale: 15,
  },
];
